version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  rc-publications:
    container_name: rc-publications-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      RABBITMQ_HOST: rc-rabbitmq
      MYSQL_HOST: rc-publications-db
      MYSQL_DB: publications
      MYSQL_USER: root
      MYSQL_PASS: secret
    ports:
      - 8004:80

  rc-publications-db:
    image: mysql:5.7
    container_name: rc-publications-db-dev
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: publications

  rc-rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"